# git-cliff changelog generator configuration file
# https://git-cliff.org/docs/configuration

[git]
filter_unconventional = false
sort_commits = "newest"
tag_pattern = "[0-9]+\\.[0-9].*"
commit_preprocessors = [
    # Keep only first line of commit message
    { pattern = "^([^\n]+)\n(?s:.*)", replace = "${1}"},
    # Pull request links in commit message
    { pattern = "\\(#([0-9]+)\\)", replace = "([#${1}](https://github.com/intgr/rocket-sentry/pull/${1}))"},
]
commit_parsers = [
    { message = "^ci:", group = "CI" },
    { message = "^feat:", group = "Feature" },
    { message = "^docs:", group = "Documentation" },
    { message = "^Update Rust crate", group = "Dependency" },
    { message = "^Update .+ requirement", group = "Dependency" },
    { message = "^Merge branch", skip = true },
    { message = "^Update actions/", skip = true },
    { message = "^Prepare for .+ release", skip = true },
]

[changelog]
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is similar to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}\
{% else %}\
    ## [unreleased]\
{% endif %}\
\n
{% for commit in commits %}\
    - \
    {% if commit.group %}**\
        {% if commit.breaking %}[Breaking] {% endif %}\
        {{ commit.group | upper_first }}:** \
    {% endif %}\
    {{ commit.message | upper_first }}
    {% if commit.author.name and commit.author.name is not matching("\\[bot\\]|Marti Raudsepp") %}
        {# keep whitespace #}  Contributed by **{{ commit.author.name }}**
    {% endif %}\
{% endfor %}\n
"""
